### ISSUE TITLE
Rename `pool_swap_fee` to `pair_swap_fee`

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/search#14]
# Goal

Update schema – rename `pool_swap_fee` field to `pair_swap_fee` (otherwise stays the same).

## Background

The backend field `pool_swap_fee` has been renamed to `pair_swap_fee` since it applies to all types of trading pairs. Currently, both values are being included in the Typesense export from Oracle. But since `pair_swap_fee` is not defined in the schema, it can't be used as a filter or sort field in `frontend`.

## Details

Faceting should be enabled on the new `pair_swap_fee` field. See tradingstrategy-ai/frontend#437

## Tasks

- [x] update [trading-entities.json](https://github.com/tradingstrategy-ai/search/blob/main/schemas/trading-entities.json) to add `pair_swap_fee`
- [x] update [trading-entities.md](https://github.com/tradingstrategy-ai/search/blob/main/docs/trading-entities.md) to add `pair_swap_fee` and mark `pool_swap_fee` as deprecated
- [x] deploy, re-populate, and wait for tradingstrategy-ai/frontend#327 to be completed and deployed (see **Deployment** below)
- [x] update [trading-entities.json](https://github.com/tradingstrategy-ai/search/blob/main/schemas/trading-entities.json) to remove `pool_swap_fee`
- [x] update [trading-entities.md](https://github.com/tradingstrategy-ai/search/blob/main/docs/trading-entities.md) to add `pool_swap_fee`

## Deployment

- [x] follow steps to [delete and re-create `trading-entities` collection](https://github.com/tradingstrategy-ai/search/blob/main/docs/troubleshooting.md#delete-and-recreate-trading-entities-collection)

Note that this task must be coordinated with tradingstrategy-ai/frontend#327. Currently, `frontend` references the old `pool_swap_fee` field name as a sort criteria. Once the schema changed is deployed, this will break.

We _could_ make the changes in multiple stages:
1. add `pair_swap_fee` to `search` schema
2. deploy – drop/re-create `search` schema
3. update `frontend` to use `pair_swap_fee`
4. deploy `frontend`
5. remove `pool_swap_fee` from `search` schema
