### ISSUE TITLE
Add support for `lending_reserve` type

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/search#15]
# Goal

Add support for `lending_reserve` type so that lending reserves can be loaded from `oracle` extract and searched on  [tradingstrategy.ai](tradingstrategy.ai).

## Details

| Field | Value / Format | New? | Comments |
| --- | --- | :---: | --- |
| `id` | `lending_reserve_567` | | |
|`type` | `lending_reserve` | | |
| `type_rank` | `4` | | Order of results in quick search<br/>Currently `exchange=1`, `pair=2`, `token=3`<br/>**Does `4` make sense?**  |
| `name` | `asset_name` | | |
| `description` | `asset_name` on `protocol_name` | | **Should this also include `chain_name`?** |
| `lending_protocol` | `protocol_name` | ✅ | |
| `supply_apr` | `supply_apr_latest` | ✅ | |
| `stable_borrow_apr` | `stable_borrow_apr_latest` | ✅ | |
| `variable_borrow_apr` | `variable_borrow_apr_latest` | ✅ | |

> **Note**
> Additional lending reserve fields may be added once they're available.
> See tradingstrategy-ai/oracle#329

## Tasks

- [x] update `schemas/trading-entities.json` with new fields
- [x] update `docs/trading-entities.md` with new info
- [x] test new schema with local instance of Typesense

## Deployment notes

The new APR fields will all be optional (and only populated for `type=lending_reserve`). The Trading Entities collection should be dropped / re-created / re-populated before the corresponding `oracle` data-extract changes are completed and deployed. See tradingstrategy-ai/oracle#405

**Comment by hieuh25** [comment]
- Order 4 sounds good to me at the moment
- Since we have only Aave v3 as protocol at the moment, I think `chain_name` should be included in the description instead of `protocol_name`, e.g: USDT on Polygon, the lending reserve badge will differ it from the token
- Alternatively we can have both chain and protocol name in description like: USDT on Aave v3 (Polygon), that doesn't look too bad for me either. There was an idea to show chain icon instead of text to make the description shorter, maybe it's the right time to do so? (cc @miohtama )

**Comment by kenkunz** [comment]
Thanks, @hieuh25!

- One reason I think it would still be beneficial to include `protocol_name` in the description is to make it more obvious that a particular result row is a lending reserve. Tokens already have the description "SYMBOL on Blockchain". I think including the `protocol_name` would help disambiguate the results (in addition to the label/tag that is shown on the left). So for example, DAI _token_ will read "DAI on Ethereum", DAI _reserve_ will read "DAI on Aave V3".
- I agree this is a good time to introduce the blockchain icon :). If we don't for some reason, then we should include it in the description – e.g., "DAI on Aave V3 (Ethereum)"
